### PR TITLE
presentation about openSUSE Kubic

### PR DESCRIPTION
**Pull request by skriesch**
I gave my first technical presentation about openSUSE Kubic at Freenode Live 2018.
Many people are interested in the technology behind openSUSE Kubic. I have extended my slides with the topic podman after questions about the difference between docker and podman, and an example plaform using podman.
Therefore I want to publish that for reusing it here.

### CODE REVIEW

**Comment by sysrich** [comment]
Hi Sarah,

Thank you for the submission but there are a number of factual and subjective inaccuracies that I think do not make your presentation suitable to be included as an official overview of the Project.

Slide 4 - This includes a number of incorrect logos, including a totally invalid Kubic logo, not the official openQA logo, "miniSUSE" (which is not an authorised mark of the openSUSE Project or SUSE) and a very old, invalid version of the openSUSE logo

Slide 5 - Wrong logo, states Kubic is based on SUSE CaaSP, when it is not.

Slide 6 - States "Created with a Docker base" - we do not. and "(part of Atomic Project)" we are not, nor is Docker (do you mean Docker Inc? they are very protective over their use of trademarks).

Slide 12 - We are not affiliated with the Atomic Project and I do not know why it's included in this presentation.

Slide 13 - Velum is not present in any openSUSE distribution.

Slide 14 - Podman is not 'an alternative' but the 'primary container runtime for users' in Kubic.

Slide 22 - We do not include the Docker Open Source Container Runtime in Kubic, so why mention which version introduced their experimental rootless support? the only container runtime with actual supported rootless features is currently Podman

Slide 30 - Again, we are not affiliated with Project Atomic and I do not understand why they are referenced in this slidedeck about Kubic.

If you could clear up these issues it could be very useful to have a slide deck like this available, thanks!

**Comment by skriesch** [comment]
About the issue openQA logo on page 4: What is wrong with the openQA logo? Where do we have another image with the name openQA? I can not find anything for that in any github repo or in the wiki.

About the issue Velum on page 13: Velum is documented as a dashboard for openSUSE Kubic here: https://kubic.opensuse.org/blog/2018-03-22-introduction/

**Comment by skriesch** [comment]
About the issue Docker version on slide 22: Some people want to know a comparison of Docker and Podman. It is well known that Docker can be run rootless now, too. Therefore I wanted to show "since when" it is possible in Docker and "why" they should use Podman instead of that.

**Comment by thkukuk** [comment]
On Mon, Dec 16, Sarah Julia Kriesch wrote:

> About the issue Velum on page 13: Velum is documented as a dashboard for
> openSUSE Kubic here: https://kubic.opensuse.org/blog/2018-03-22-introduction/

That blog is from March 2018, there is at least one newer blog from
August 2018 were we write that the March plan is outdated and will not
be done.

Blogs are valid for the time they are written, not forever.

**Comment by skriesch** [comment]
Project Atomic is removed everywhere. Other issues are fixed. The fast missing thing is an alternative openQA logo.

**Comment by sysrich** [comment]
The valid openQA logo is the one in the codebase
https://github.com/os-autoinst/openQA/blob/2d0b795068ad7d68e907b53ea28011ae962a8218/assets/images/logo.svg

No additional text is the key there :)

**Comment by skriesch** [comment]
openQA logo is updated. Thanks! :)

**Comment by sysrich** [comment]
Thanks!

**Pull request merged**
